#!/bin/bash
# This hook is run after this virtualenv is activated.

echo 'Set DJANGO_SETTINGS_MODULE="videothumbs_project.settings.dev"'
export DJANGO_SETTINGS_MODULE="videothumbs_project.settings.dev"